### ISSUE TITLE
Include filter throws type error

### ISSUE THREAD

**Issue by antolinos** [ral-facilities/datagateway-api#377]
Hi,

**Description**:
I am experiencing some issues with the seach-api. It seems that the include filter throws an error. Example:
```
http://localhost:5000/search-api/Documents?filter={"include":[{"relation":"members"}],"limit":50}
```
will return:
```
{
  "error": {
    "message": "cannot unpack non-iterable method object",
    "name": "TypeError",
    "statusCode": 400
  }
}
```

The traceback is:
```
[2022-09-06 15:46:49,766] {helpers:helpers.py:wrapper_error_handling:56} ERROR - ('cannot unpack non-iterable method object',)
Traceback (most recent call last):
  File "/home/demariaa/Software/workspaces/icat/datagateway-api/datagateway_api/src/search_api/helpers.py", line 46, in wrapper_error_handling
    return method(*args, **kwargs)
  File "/home/demariaa/Software/workspaces/icat/datagateway-api/datagateway_api/src/resources/search_api_endpoints.py", line 41, in get
    entities = get_search(entity_name, filters)
  File "/home/demariaa/Software/workspaces/icat/datagateway-api/datagateway_api/src/search_api/session_handler.py", line 44, in wrapper_client_manager
    return method(*args, **kwargs)
  File "/home/demariaa/Software/workspaces/icat/datagateway-api/datagateway_api/src/search_api/helpers.py", line 189, in get_search
    filter_handler.apply_filters(query)
  File "/home/demariaa/Software/workspaces/icat/datagateway-api/datagateway_api/src/common/filter_order_handler.py", line 62, in apply_filters
    query_filter.apply_filter(query)
  File "/home/demariaa/Software/workspaces/icat/datagateway-api/datagateway_api/src/search_api/filters.py", line 194, in apply_filter
    panosc_entity_name, icat_field_name = mappings.get_icat_mapping
TypeError: cannot unpack non-iterable method object
```

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by antolinos** [comment]
I close the issue un til further investigation. This can be due to my local deployment and not the main branch.
